apiVersion: v1
kind: Service
metadata:
  name: weather-station-1
spec:
  selector:
    app: weather-station-1
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-station-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-station-1
  template:
    metadata:
      labels:
        app: weather-station-1
    spec:
      containers:
        - name: weather-station-1
          image: nourwalid/weather_station:latest
          env:
            - name: ID
              value: "1"
            - name: KAFKA_SERVER
              value: "kafka-service:9092"
          ports:
            - containerPort: 8080