apiVersion: v1
kind: Service
metadata:
  name: central-station-service
spec:
  selector:
    app: central-station
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-station
spec:
  selector:
    matchLabels:
      app: central-station
  replicas: 1
  template:
    metadata:
      labels:
        app: central-station
    spec:
      containers:
      - name: central-station
        image: nourwalid/central_station:latest
        env:
          - name: KAFKA_SERVER
            value: "kafka-service:9092"
        volumeMounts:
        - name: my-volume
          mountPath: /app/data
        ports:
        - containerPort: 8080
      volumes:
      - name: my-volume
        persistentVolumeClaim:
          claimName: shared-pvc