resources:
  - 0.yaml
  - 1.yaml
  # - 2.yaml
  # - 3.yaml
  # - 4.yaml
  # - 5.yaml
  # - 6.yaml
  # - 7.yaml
  # - 8.yaml
  # - 9.yaml
  - api-weather-station.yaml
  - rain-detector.yaml
  - central-station.yaml