apiVersion: v1
kind: Service
metadata:
  name: es-connector-service
spec:
  selector:
    app: es-connector
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-connector
spec:
  selector:
    matchLabels:
      app: es-connector
  replicas: 1
  template:
    metadata:
      labels:
        app: es-connector
    spec:
      containers:
      - name: es-connector
        image: nourwalid/es_connector:latest
        env:
          - name: ES_SERVER
            value: "http://elasticsearch:9200"
        volumeMounts: 
        - name: shared-volume
          mountPath: /app/data
      volumes: 
      - name: shared-volume
        persistentVolumeClaim:
          claimName: shared-pvc


