apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    app: kafka-broker
    

spec:
  ports:
  - port: 9092
  selector:
    app: kafka-broker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-broker
  name: kafka-broker

spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      hostname: kafka-broker
      containers:
      - env:
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "true"
        - name: KAFKA_ENABLE_KRAFT
          value: "false"
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-service:2181
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://:9092
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka-service:9092
        image: bitnami/kafka:latest
        imagePullPolicy: IfNotPresent
        name: kafka-broker
        ports:
        - containerPort: 9092